import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import JSZip from "jszip";

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const { projectId } = await req.json();

    const project = await prisma.project.findFirst({
      where: { id: projectId, userId: session.user.id },
      include: { files: true },
    });

    if (!project) return NextResponse.json({ error: "Not found" }, { status: 404 });

    const zip = new JSZip();
    const root = zip.folder(project.name.replace(/[^a-zA-Z0-9-_]/g, "-"))!;

    for (const file of project.files) {
      root.file(file.path, file.content);
    }

    root.file(
      "README.md",
      `# ${project.name}\n\n${project.description}\n\n## Generated by BuildAI\n\nGenerated from prompt:\n> ${project.prompt}\n\n## Setup\n\n1. Open \`index.html\` in your browser or serve with a local server\n2. Customize the content as needed\n\n---\n*Built with [BuildAI](${process.env.NEXT_PUBLIC_APP_URL})*`
    );

    const buffer = await zip.generateAsync({ type: "arraybuffer", compression: "DEFLATE" });

    return new Response(buffer as ArrayBuffer, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${project.name}.zip"`,
      },
    });
  } catch {
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}
